src/controllers/userController.js, src/middlewares/access.js, src/routes/ratingRouter.js, src/routes/userRoutes.js
=> added isManager middleware

.env.example, src/routes/userRoutes.js
=> fixes on isManager

package.json, src/controllers/authController.js, src/controllers/mailListController.js, src/database/migrations/20210803043632-create-allowed-emails.js, src/database/models/allowedemails.js, src/database/seeders/20210803050146-allowedEmails.js, src/helpers/response.js, src/routes/allowedEmailsRouter.js, src/routes/index.js, src/services/allowedEmailsService.js, src/services/userService.js, src/swagger/emails/allowedEmails.js, src/swagger/index.js, src/validation/allowedEmailsValidation.js, src/validation/schema/index.js
This PR holds changes to create/delete a list of authorized emails (this task can only be performed by the manager)
- create a table of allowed emails
- a user with a manager role can add one or many emails
- a user with a manager role can remove one or many emails
- non-authorized emails are not allowed to sign in except if they are with a **@andela** 
- pull the changes 
- checkout to `ft-AuthorizedEmailList`
- run yarn install and yarn dev
- login as a manager then add or remove the emails from the approved emails list
N/A
[]()
N/A
N/A
=> adds and deletes authorized emails

src/controllers/cohortsController.js, src/controllers/programsController.js, src/controllers/ratingController.js, src/controllers/userController.js, src/database/migrations/20191018140915-create-average-rating.js, src/database/migrations/20210802153340-create-cohorts.js, src/database/migrations/20210802154320-create-programms.js, src/database/migrations/20210802154414-alter_users_table.js, src/database/migrations/20210802155802-alter_ratings_table.js, src/database/models/cohort.js, src/database/models/program.js, src/database/models/rating.js, src/database/models/user.js, src/middlewares/cohort.js, src/middlewares/users.js, src/routes/cohortsRoute.js, src/routes/index.js, src/routes/programsRouter.js, src/routes/ratingRouter.js, src/routes/userRoutes.js, src/services/cohortService.js, src/services/programsService.js, src/services/ratingService.js, src/services/userService.js, src/swagger/cohorts/cohort.js, src/swagger/index.js, src/swagger/programs/programs.js, src/swagger/users/users.js, src/validation/cohortsValidator.js, src/validation/programsValidator.js
=> add programs and cohorts

.eslintrc.json, .prettierrc.json, package.json, src/controllers/ratingController.js, src/helpers/index.js, src/middlewares/users.js, src/services/programsService.js, src/services/ratingService.js
Compute the average for each program the trainee has a rating for.
- Clone the repository then checkout to `ft-compute-program-ratings`
- Run `npm install` to add all project dependencies the `npm run dev` to test all features above
=> feat(ratings): compute program rating

src/routes/programsRouter.js
- able to fetch programs when logged in as trainee.
This is a chore  that allows a trainee to fetch the programs
able to fetch all programs when logged in as trainee
`git pull` from develop
`git checkout ch-programs` to go to the branch
`yarn dev`
N/A
[]()
N/A
N/A
=> chore(programs route): fetch programs as trainee

src/controllers/mailListController.js, src/routes/allowedEmailsRouter.js, src/services/allowedEmailsService.js, src/swagger/emails/allowedEmails.js
Just an additional endpoint to retrieve all authorized emails
- checkout on ft-AuthorizedEmailList branch
- run yarn dev
- use postman and  send a GET request at /api/v1/emails
N/A
[]()
N/A
N/A
=> Ft authorized email list

.gitignore, package.json, src/swagger/index.js
=> Setup heroku cd pipeline

src/controllers/userController.js
=> program null on cohort change

README.md
Add README file
See #20 
Would be good if everyone collaborated by adding all necessary instructions and badges.
N/A
N/A
[]()
N/A
N/A
=> feat: README file

package.json, src/controllers/cohortsController.js, src/controllers/programsController.js, src/index.js, src/routes/cohortsRoute.js, src/routes/programsRouter.js, src/services/cohortService.js, src/services/programsService.js, src/swagger/cohorts/cohort.js, src/swagger/emails/allowedEmails.js
update and delete cohort functionalities.
- clone repo or pull changes from remote
- got to `ft-program-cohort-crud` branch to test above stated features.
=> feat(cohorts): update and delete

src/middlewares/users.js
Cange the status of error n rating 
- fix error status when rating a trainee with no program from 400 to 401
1.  clone this repo
1.  create a `.env` file and copy all variables from `.env.example`
1. run `yarn install`
1.  go to `http://localhost:3000/api/v1/ratings/rate` and send ratings with no program
N/A
b7SAR34
N/A
N/A
=> Fix(rating): rating error status code

app.json, package.json, src/controllers/attendanceController.js, src/controllers/sessionsController.js, src/database/migrations/20210913140415-create-attendance.js, src/database/migrations/20210913150706-create-sessions.js, src/database/models/attendance.js, src/database/models/sessions.js, src/database/seeders/20210803050146-allowedEmails.js, src/database/seeders/20210913150827-sessions.js, src/middlewares/attendance.js, src/routes/attendance.js, src/routes/index.js, src/routes/sessions.js, src/services/attendanceService.js, src/services/sessionsService.js, src/services/userService.js
=> add attendance

src/routes/sessions.js
=> remove sessions

package.json, src/controllers/userController.js, src/database/config.js
> Update node version
- update app to use node 12.x and above
- added envVar of develop
- update dev script to use seed:undo
- uninstalling unused packaes
1.  clone this repo
1. Make sure you are using the latest version on node and
1.  create a `.env` file and copy all variables from `.env.example`
1. run `yarn install`
1.  go to `http://localhost:3000/` 
N/A
[]()
N/A
N/A
=> chore(node version): update node version

src/middlewares/attendance.js, src/routes/sessions.js, src/services/attendanceService.js
=> avoid deleting sesion associated with attendance

src/controllers/cohortsController.js, src/routes/cohortsRoute.js, src/services/userService.js, src/swagger/cohorts/cohort.js
Provide all ratings within a cohort and filter them by date
- Clone the repo or pull changes from the remote the go to `ft-export-cohort` branch
- Run `yarn install` then `yarn dev` to test all the features stated above.
=> Feature(performance): export ratings by cohort

.env.example, app.json, src/controllers/authController.js, src/controllers/ratingController.js, src/controllers/userController.js, src/database/migrations/20211109171815-create-updated-ratings.js, src/database/models/rating.js, src/database/models/updatedratings.js, src/helpers/index.js, src/middlewares/users.js, src/routes/ratingRouter.js, src/services/ratingService.js, src/services/updatedRatings.js, src/utils/seniorManagers.js
=> modify ratings

src/controllers/userController.js, src/database/seeders/20210803050146-allowedEmails.js, src/database/seeders/20210916091551-user.js
> - check if user is a senior manager
> - check if user is a senior manager
> - pull & checkout `ft-senior-managers` branch
=> feat senior manager

src/services/userService.js
> - Export email
> - add email attribute
> - checkout `ft-export-csv` branch
=> feat add email attribute
